[package]
name = "rust-malloc"
version = "0.1.0"
authors = ["suzusuzu <s.suzugamine@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.112"
jemalloc-sys = "0.3.2"